### ISSUE TITLE
Migrate Labels to Tags

### ISSUE THREAD

**Issue by RamanDamayeu** [opendatadiscovery/odd-collector-profiler#27]
Initially, "labels" played role of tags for Data Structure (for columns) and Tags were used for the rest of the objects.
With [Get rid of labels](https://github.com/opendatadiscovery/odd-platform/issues/1425) issue Platform processes Tags for both columns and and data entities. 
Starting with the Platform [0.17.0](https://github.com/opendatadiscovery/odd-platform/releases/tag/0.17.0) there should be only Tags and not Labels in the system.

Data Profiler still used Labels when running Auto Labeling tasks. We need to map Labels to be sent as Tags to the platform.

**Comment by ValeriyWorld** [comment]
@RamanDamayeu everything working as expected. I mistakenly used odd-platform image of 0.15.0 version, so the odd-collector-profiler was sending labels instead of tags. Once I have updated my image to the newest 0.24.1 version - tags appeared with no changes in code.
<img width="1437" alt="image" src="https://github.com/opendatadiscovery/odd-collector-profiler/assets/23039566/8d263cc1-7bcd-41cb-8030-bd4356fddb7b">

**Comment by RamanDamayeu** [comment]
Thanks for checking!
